# General mod settings
[general]
    # SETTING THESE SERVER SIDE SETTINGS TO FALSE WILL OVERRIDE ANY OF THE SAME CLIENT SETTINGS THAT ARE SET TO TRUE (for all clients)
    # 将这些服务器端设置设为 false 将会覆盖所有客户端上设置为 true 的相同客户端设置（对所有客户端生效）
    dummySetting = true
    # Disable new dynamic gui system and use old simple visual.
    # 禁用新的动态 GUI 系统并使用旧的简单视觉效果。
    dynamicGuiUseOldSimpleGUIVisual = true
    # Delay in ticks before sending a new image of a gui to other clients, 10 = twice a second, 0 = no delay, 20 = once a second, more frequent might affect performance and network load
    # 向其他客户端发送 GUI 新图像之前的延迟（以 tick 为单位），10 = 每秒两次，0 = 无延迟，20 = 每秒一次，更频繁可能会影响性能和网络负载
    # Range: > 5
    dynamicGuiTickSendRateOfGUIUpdates = 10
    # If enabled, only sends the initial image of a players gui, does not constantly update after it's been opened.
    # 如果启用，则仅发送玩家 GUI 的初始图像，打开后不会持续更新。
    dynamicGuiDontSendConstantGUIUpdates = true
    # Blur is used to prevent nasty aliasing/flicker artifacts at the cost of clarity
    # 模糊用于防止难看的锯齿/闪烁伪影，但会牺牲清晰度
    # Range: 0 ~ 2
    dynamicGuiBlurLevel = 1
    # Adjust the size of the circle used to cut off extra info beyond their main area of their gui, visual issues may occur of too big. Set to -1 to disable
    # 调整用于裁剪 GUI 主要区域之外额外信息的圆形大小，如果太大可能会出现视觉问题。设置为 -1 以禁用
    # Range: 4.9E-324 ~ 1.7976931348623157E308
    dynamicGuiSizeRadiusInPixelsToShow = 112.0
    # Show a clients entire screen instead of using dynamicGuiSizeRadiusInPixelsToShow for a circle fade in a 512x512 area, WARNING: experimental, has cpu and network performance impact. Tweak dynamicGuiSizeRadiusInPixelsToShow to -1 or something large if you use this setting.
    # 显示客户端的整个屏幕，而不是使用 dynamicGuiSizeRadiusInPixelsToShow 在 512x512 区域内进行圆形淡入，警告：实验性的，会对 CPU 和网络性能产生影响。如果使用此设置，请将 dynamicGuiSizeRadiusInPixelsToShow 调整为 -1 或更大的值。
    dynamicGuiShowClientsEntireScreen = false
    # Disables the background rendering for most guis, might hide things like JEI or other things count as background rendering
    # 禁用大多数 GUI 的背景渲染，可能会隐藏 JEI 或其他被视为背景渲染的内容
    dynamicGuiDisableBackgroundRendering = true
    # Show items being transferred between player and container
    # 显示在玩家和容器之间传输的物品
    showItemsBeingTransferredBetweenPlayerAndContainer = false
    # How close another player has to be to another player to see what they're doing in GUI, item transferring, mouse movement, etc
    # 另一个玩家必须离多近才能看到他们在 GUI 中做什么，物品传输，鼠标移动等
    # Range: > 0
    distanceRequiredToShowGUIInfo = 1
    # Enables or disables idle visual in the server player list tab screen
    # 启用或禁用服务器玩家列表标签屏幕中的空闲视觉效果
    showIdleStatesInPlayerList = false
    # Enables or disables idle visual above player head
    # 启用或禁用玩家头顶上方的空闲视觉效果
    showIdleStatesInPlayerAboveHead = false
    # Setting false disables all animations
    # 设置为 false 将禁用所有动画
    showPlayerAnimations = true
    # Enables or disables typing animation
    # 启用或禁用打字动画
    showPlayerAnimation_Typing = true
    # Enables or disables idle animation
    # 启用或禁用空闲动画
    showPlayerAnimation_Idle = false
    # Enables or disables the non typing animations used when showing the open Gui, such as head looking, arms moving up, arms pointing and clicking
    # 启用或禁用显示打开的 GUI 时使用的非打字动画，例如头部观看、手臂向上移动、手臂指向和点击
    showPlayerAnimation_Gui = true
    # Show any Gui they're using that isn't chat typing related in world
    # 在世界中显示他们正在使用的任何与聊天打字无关的 GUI
    showPlayerActiveNonChatGui = true
    # Show the chat typing Gui in world
    # 在世界中显示聊天打字 GUI
    showPlayerActiveChatGui = true
    # Show 'Player is typing...' on the chat screen
    # 在聊天屏幕上显示“玩家正在输入...”
    screenTypingVisible = true
    # Plays a sound when a player opens some Guis
    # 当玩家打开一些 GUI 时播放声音
    playScreenOpenSounds = false
    # Plays a sutble sound when a player clicks their mouse in a Gui
    # 当玩家在 GUI 中单击鼠标时播放细微的声音
    playMouseClickSounds = false
