#General mod settings
[general]
    #SETTING THESE CLIENT SIDE SETTINGS TO FALSE WILL OVERRIDE ANY OF THE SAME SERVER SETTINGS THAT ARE SET TO TRUE (for your client only).
    #设置这些客户端设置设为 false 将会覆盖所有服务器上设置为 true 的相同服务器设置（仅对您的客户端生效）。
    dummySetting = true
    #Sends relative mouse position and clicking
    #发送相对鼠标位置和点击
    sendMouseInfo = false
    #Sends a calculated rate of typing. If off, uses a default value on server
    #发送计算的打字速度。如果关闭，则在服务器上使用默认值
    sendTypingSpeed = true
    #Sends when you open a Gui, and what Gui
    #发送您何时打开 GUI 以及什么 GUI
    sendActiveGui = true
    #Sends when you go idle / return
    #发送您何时进入空闲状态/返回
    sendIdleState = false
    #Enables or disables idle visual in the server player list tab screen
    #启用或禁用服务器玩家列表标签屏幕中的空闲视觉效果
    showIdleStatesInPlayerList = true
    #Enables or disables idle visual above player head
    #启用或禁用玩家头顶上方的空闲视觉效果
    showIdleStatesInPlayerAboveHead = false
    #Setting false disables all animations
    #设置为 false 将禁用所有动画
    showPlayerAnimations = true
    #Enables or disables typing animation
    #启用或禁用打字动画
    showPlayerAnimation_Typing = true
    #Enables or disables idle animation
    #启用或禁用空闲动画
    showPlayerAnimation_Idle = false
    #Enables or disables the non typing animations used when showing the open Gui, such as head looking, arms moving up, arms pointing and clicking
    #启用或禁用显示打开的 GUI 时使用的非打字动画，例如头部观看、手臂向上移动、手臂指向和点击
    showPlayerAnimation_Gui = true
    #Show any Gui they're using that isn't chat typing related in world
    #在世界中显示他们正在使用的任何与聊天打字无关的 GUI
    showPlayerActiveNonChatGui = true
    #Show the chat typing Gui in world
    #在世界中显示聊天打字 GUI
    showPlayerActiveChatGui = true
    #This is for the older non dynamic GUI only. If there isnt an exact Gui available for what the player is using, it will show the Chest Gui. If this is false, it will show nothing, lots of modded Guis will use this for now
    #这仅适用于较旧的非动态 GUI。如果没有与玩家正在使用的 GUI 完全匹配的 GUI，它将显示 Chest Gui。如果此项为 false，则不显示任何内容，许多 modded Gui 现在将使用此项
    showPlayerActiveGuiIfNotExactMatch = false
    #Show 'Player is typing...' on the chat screen
    #在聊天屏幕上显示“玩家正在输入...”
    screenTypingVisible = true
    #Adjust the X position where the 'Player is typing...' text shows in the chat Gui
    #调整“玩家正在输入...”文本在聊天 GUI 中显示的 X 坐标
    #Range: > 0
    screenTypingRelativePosition_X = 0
    #Adjust the Y position where the 'Player is typing...' text shows in the chat Gui
    #调整“玩家正在输入...”文本在聊天 GUI 中显示的 Y 坐标
    #Range: > 0
    screenTypingRelativePosition_Y = 0
    #Max characters allowed before it switches to using string set in screenTypingMultiplePlayersText
    #允许的最大字符数，超过此字符数将切换为使用 screenTypingMultiplePlayersText 中设置的字符串
    #Range: > 0
    screenTypingCharacterLimit = 50
    #String to use when too many people are typing determined by screenTypingCharacterLimit
    #当有太多人正在输入（由 screenTypingCharacterLimit 确定）时使用的字符串
    screenTypingMultiplePlayersText = "Several people are typing"
    #String to use next to the typing player(s) name
    #在输入玩家姓名旁边使用的字符串
    screenTypingText = " is typing"
    #Plays a sound when a player opens some Guis
    #当玩家打开一些 GUI 时播放声音
    playScreenOpenSounds = false
    #Plays a sutble sound when a player clicks their mouse in a Gui
    #当玩家在 GUI 中单击鼠标时播放细微的声音
    playMouseClickSounds = false
    #Adjusts the size of the gui visual that appears infront of a player, 2 = twice the size
    #调整出现在玩家面前的 GUI 视觉效果的大小，2 = 两倍大小
    #Range: 0.1 ~ 1.7976931348623157E308
    particleSizeScale = 1.0
    #Delay between ticks your client will accept and update new image of another players gui, you can only increase the delay from what the server/other client is set to, 10 = twice a second
    #客户端接受和更新其他玩家 GUI 新图像之间的延迟（以 tick 为单位），您只能增加服务器/其他客户端设置的延迟，10 = 每秒两次
    #Range: > 0
    tickReceiveAndRenderRateOfGUIUpdates = 10
    #Privacy setting, if you dont want to send very detailed info of your screen for everyone to see and instead use the old basic gui visual, set this to true
    #隐私设置，如果您不想发送屏幕的非常详细的信息供所有人查看，而是使用旧的基本 GUI 视觉效果，请将其设置为 true
    dontSendDetailedGUIInfo = true
    #Privacy setting, if you dont want to show the items you are transferring to and from yourself and containers, set this to true
    #隐私设置，如果您不想显示您自己与容器之间传输的物品，请将其设置为 true
    dontSendItemInfo = true
